### ISSUE TITLE
Cannot pass python class object into jinja template, defaults to 'markupsafe.Markup object'

### ISSUE THREAD

**Issue by zmcddn** [pallets/jinja#960]
`jinja macros` doesn't work as expected, python class doesn't get passed into jinja macros.

jinja template render super funciton returns `markupsafe.Markup object`

---

## Expected Behavior

Python class object should be passed to jinja macros and templates. 
Code works in Django 1.11 but not Django 2.1

## Actual Behavior

Throws out error code:

```jinja
jinja2.exceptions.UndefinedError: 'markupsafe.Markup object' has no attribute 'full_ask_url'
```

## Template Code

Jinja Template:

```jinja
{% set search_state=search_state|get_empty_search_state %}
href="{{ search_state.full_ask_url() }}{% if group %}{% if '?' in search_state.full_ask_url() %}&amp;{% else %}?{% endif %}group_id={{ group.id }}{% endif %}">
```

Django:

```jinja
from jinja2 import Template as _Jinja2Template

class Template(_Jinja2Template):
    '''Fixes the incompabilites between Jinja2's template class and
    Django's.

    The end result should be a class that renders Jinja2 templates but
    is compatible with the interface specfied by Django.

    This includes flattening a ``Context`` instance passed to render
    and making sure that this class will automatically use the global
    coffin environment.
    '''

    def render(self, context=None):
        """Differs from Django's own render() slightly in that makes the
        ``context`` parameter optional. We try to strike a middle ground
        here between implementing Django's interface while still supporting
        Jinja's own call syntax as well.
        """
        if context is None:
            context = {}
        else:
            context = dict_from_django_context(context)
        assert isinstance(context, dict)  # Required for **-operator.

        signals.template_rendered.send(sender=self, template=self, context=Context(context))
        return super(Template, self).render(**context)
```

## Full Traceback
```pytb
Internal Server Error: /en/questions/
Traceback (most recent call last):
  File "D:\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "d:\views\readers.py", line 294, in questions
    return render(request, 'main_page.html', template_data)
  File "D:\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "d:\skins\template_backends.py", line 86, in render
    return self.template.render(context)
  File "d:\deps\coffin\template\__init__.py", line 56, in render
    return super(Template, self).render(**context)
  File "D:\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "d:\templates\main_page.html", line 30, in top-level template code
    {% set search_state=search_state|get_empty_search_state %}
  File "d:\templates\two_column_body.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "d:\templates\base.html", line 37, in top-level template code
    {% include "widgets/header.html" %} {# Logo, user tool navigation and meta navitation #}
  File "d:\templates\widgets\header.html", line 39, in top-level template code
    {% include "widgets/ask_button.html" %}
  File "d:\templates\widgets\ask_button.html", line 6, in top-level template code
    href="{{ search_state.full_ask_url() }}{% if group %}{% if '?' in search_state.full_ask_url() %}&amp;{% else %}?{% endif %}group_id={{ group.id }}{% endif %}">
jinja2.exceptions.UndefinedError: 'markupsafe.Markup object' has no attribute 'full_ask_url'
```

## Your Environment
- Django: 2.1.7
- Jinja: 2.10
- python: 3.7.1

**Comment by davidism** [comment]
I'm not familiar with using Jinja with Django, but I can't reproduce this issue with a basic example. I created template filter that takes an object and returns an object, set a variable to that result, and accessed a property of the object, and it worked as expected.

Seems like `get_empty_search_state` is returning a `Markup` object or calling `escape`. You'll need to address that there, it's not an issue with Jinja.

```python
from jinja2 import Environment

class Thing:
    def __init__(self, name, parent=None):
        self.name = name
        self.parent = parent

def get_parent(value):
    return value.parent

e = Environment(trim_blocks=True)
e.filters["get_parent"] = get_parent
t = e.from_string("{% set p = value|get_parent%}{{ p.name }}")
print(t.render(value=Thing("child", parent=Thing("parent"))))
```

```
parent
```
