### ISSUE TITLE
MarkupSafe 2.1.0 gives ImportError(soft_unicode) for Jinja2 2.11.3

### ISSUE THREAD

**Issue by seedhisadak** [pallets/jinja#1587]
Upon installing and using Jinja2==2.11.3, the dependency requirement is 
```
MarkupSafe [required: >=0.23]
```

This installs the latest `MarkupSafe==2.1.0` which gives the following error when using the Jinja2 packages
```
File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
```

Note: This works fine with `MarkupSafe 2.0.1`

Environment:

- Python version: 3.7.12
- Jinja2 version: 2.11.3

**Comment by memsharded** [comment]
> They removed soft_unicode and one has to use soft_str instead.

Yes, but not something that consumers of Jinja2 2.11.3 can do right? We have tons of released versions in production that are locked on Jinja2 2.11, and releasing patches for all is going to be painful. A bit unexpected that MarkupSafe is breaking in this way in minor versions.

**Comment by seedhisadak** [comment]
Wouldn't it be possible to fix the dependency to 

```
MarkupSafe [required: >=0.23, <=2.0.1]
```

**Comment by ivan2angelov** [comment]
I have same problem. Please fix jinja2 markupsafe

**Comment by mailtosumitrai** [comment]
@ivan2angelov I created similar issue in https://github.com/pallets/jinja/issues/1585 and I got this answer

> Jinja 2.x has not been supported for some time. Upgrade Jinja, and use something like pip-tools to pin your dependencies.

**Comment by heikkima** [comment]
https://github.com/pallets/jinja/pull/1589

**Comment by EnricoRiccardi** [comment]
bump, it breaks our pipelines too. Same error.

**Comment by seedhisadak** [comment]
Quick note, to fix our pipelines we just pinned the `MarkupSafe` version in our requirements file, example `requirements.txt` file

```
Flask==1.1.4  # May 2021 # required: >=0.10
MarkupSafe==2.0.1  # required is >=0.23 but latest 2.1.0 gives import error
```

**Comment by aditya-kar** [comment]
> Quick note, to fix our pipelines we just pinned the `MarkupSafe` version in our requirements file, example `requirements.txt` file
> 
> ```
> Flask==1.1.4
> MarkupSafe==2.0.1  # required is >=0.23 but latest 2.1.0 gives import error
> ```

We did the same and we'll probably start using pip-tools to pin all dependencies going forward.

> `
> MarkupSafe~=2.0.1
> `

**Comment by davidism** [comment]
You are using an unsupported version of Jinja. Whether you can update or not, please also see https://hynek.me/articles/semver-will-not-save-you/, then use a tool such as pip-tools to pin your dependencies.
