### ISSUE TITLE
Strange random crashes: TypeError: __init__() missing 1 required positional argument: 'undefined'

### ISSUE THREAD

**Issue by Kwpolska** [pallets/jinja#838]
Since 2.10, a previously working and usually-looking template crashes with a cryptic error. My futile debugging attempts hint at `LoopContext`’s new `undefined` argument.

I can only reproduce randomly. Any attempts to minimize `test.j2` lead to the error not occurring. And then other weird things happen.

## Template Code

test.j2:

```jinja
{#  -*- coding: utf-8 -*- #}
{% extends 'base.tmpl' %}
{% import 'project_helper.tmpl' as project with context %}
{% block content %}
    <header class="page-header">
        <h1>{{ title }}</h1>
    </header>

{% if featured %}
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    {% for p in featured %}
    <li data-target="#carousel-example-generic" data-slide-to="{{ loop.index0 }}"
{% if loop.index0 == 0 %}
 class="active"
{% endif %}
></li>
    {% endfor %}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    {% for p in featured %}
    <div class="item
{% if loop.index0 == 0 %}
active
{% endif %}
">
    <a href="{{ p.permalink() }}">
      <img src="{{ p.meta('previewimage') }}" alt="{{ p.title() }}">
    </a>
      <div class="carousel-caption">
        <h3>{{ p.title() }} {{ project.status(p.meta('status')) }}</h3>
        <p>{{ p.description() }}</p>
        <a href="{{ p.permalink() }}" class="btn btn-primary"><i class="fa fa-info-circle"></i> View details</a>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
{% endif %}

<h2>All projects</h2>

    <ul class="project-list">
    {% for p in projects %}
        <li class="project project-sort-{{ p.meta('sort') }}"><a href="{{ p.permalink() }}">{{ p.title() }}</a> {{ project.status(p.meta('status')) }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}
```

base.tmpl:
```jinja2
{% block content %}
{% endblock %}
```

project_helper.tmpl: empty

## Python driver code
```py
import os
import io
import json
try:
    import jinja2
    from jinja2 import meta
except ImportError:
    jinja2 = None  # NOQA


name = "jinja"
lookup = None
dependency_cache = {}
per_file_cache = {}

cache_folder = '/tmp/jinjaCache'
if not os.path.exists(cache_folder):
    os.mkdir(cache_folder)
cache = jinja2.FileSystemBytecodeCache(cache_folder)
lookup = jinja2.Environment(bytecode_cache=cache)
# lookup = jinja2.Environment()
lookup.trim_blocks = True
lookup.lstrip_blocks = True
lookup.filters['tojson'] = json.dumps
lookup.globals['enumerate'] = enumerate
lookup.globals['isinstance'] = isinstance
lookup.globals['tuple'] = tuple
lookup.loader = jinja2.FileSystemLoader([os.getcwd()], encoding='utf-8')

template = lookup.get_template("test.j2")
print(template.render(featured=[1, 2, 3]))
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    print(template.render(featured=[1, 2, 3]))
  File "/Volumes/RAMDisk/jinja/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Volumes/RAMDisk/jinja/jinja2/environment.py", line 1009, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Volumes/RAMDisk/jinja/jinja2/environment.py", line 781, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/RAMDisk/jinja/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Volumes/RAMDisk/test.j2", line 5, in top-level template code
    {% for p in featured %}
TypeError: __init__() missing 1 required positional argument: 'undefined'
```

## Your Environment
* Python version: 3.6.5
* Jinja version: 2.10/GitHub master (e1e7735)
* reproduces reliably in Nikola

According to `git bisect`, it happens since commit 9bdb547b0ebc3d2bfd171e2693f3223ff115b4bf.

**Comment by davidism** [comment]
Try removing `cache_folder` and starting from a fresh cache.

**Comment by Kwpolska** [comment]
Okay, that’s embarrassing. The cache seems to be the culprit, removing it fixes everything.

That said, how is that cache invalidated? Or is it not touched ever?
