### ISSUE TITLE
Jinja<3.0 does not work with MarkupSafe>=2.0

### ISSUE THREAD

**Issue by gherceg** [pallets/jinja#1805]
The answer may simply be that only the latest version of jinja is expected to work, but I wanted to at least create this issue.

Version 2.11.3 only specifies a version of `MarkupSafe>=0.23` with no upper bound. As of [MarkupSafe v2.1.0](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0), support for the method `soft_unicode` that Jinja depends on has been removed. Because there is no upper bound, when installing jinja<3.0, the latest version of MarkupSafe is pulled which is not compatible.

The reproduce, in a new python environment, install jinja2==2.11.3:

`pip install jinja2==2.11.3`

Then open a python shell and attempt to import `import jinja2` to see the ImportError.
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/grahamherceg/.pyenv/versions/jinja-test/lib/python3.9/site-packages/markupsafe/__init__.py)
```

Dependency versions should have an upper bound explicitly set to ensure compatibility as new versions are released.

Environment:

- Python version: 3.9
- Jinja version: 2.11.3

**Comment by ThiefMaster** [comment]
There are SO many issues on this topic already. TL;DR you should ping your transitive dependencies and not at a later point simply install an old version and expect it to work.

**Comment by davidism** [comment]
> I wanted to at least create this issue

Be sure to search for previous issues first. This is a duplicate.

**Comment by davidism** [comment]
You are using an unsupported version of Jinja, please update to the latest version (3.1.2) if possible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates.
