### ISSUE TITLE
ImportError: cannot import name 'ASYNC_FILTERS' from partially initialized module 'jinja2.asyncfilters'

### ISSUE THREAD

**Issue by sscherfke** [pallets/jinja#1144]
## Expected Behavior
`jinja2.asyncfilters` should be importable.

## Actual Behavior
The import fails tue to circular dependencies (see next section).

## Template Code
—

## Full Traceback
```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$PREFIX/lib/python3.8/site-packages/jinja2/asyncfilters.py", line 4, in <module>
    from .asyncsupport import auto_aiter
  File "$PREFIX/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 264, in <module>
    patch_all()
  File "$PREFIX/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 169, in patch_all
    patch_filters()
  File "$PREFIX/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 161, in patch_filters
    from .asyncfilters import ASYNC_FILTERS
ImportError: cannot import name 'ASYNC_FILTERS' from partially initialized module 'jinja2.asyncfilters' (most likely due to a circular import) ($PREFIX/lib/python3.8/site-packages/jinja2/asyncfilters.py)
```

## Your Environment
* Python version: 3.7 and 3.8 on Linux and macOS
* Jinja version: 2.11.*

The import works fine in 2.10 but fails in 2.11.0 and 2.11.1

**Comment by davidism** [comment]
This is due to #806 which made enabling async support lazy, so it isn't initialized until an async environment is created. There was actually still a circular import in 2.10, but it was hidden because importing `jinja2` automatically imported `asyncsupport` first.

You need to import `jinja2.asyncsupport` first, then importing `jinja2.asyncfilters` will work.

**Comment by sscherfke** [comment]
Thanks for the quick answer.

I was updating a Conda recipe for jinja2 which imports that module as a single-op in the tests-section. I'll just skip that test then. :)
